---
swagger: "2.0"
info:
  version: "v2"
  title: "wss-lettergenerator-services-web"
basePath: "/wss-lettergenerator-services-web/rest"
tags:
- name: "letters"
paths:
  /letters/v1:
    get:
      tags:
      - "letters"
      summary: "Get List of Letters"
      description: "Returns list of letters for user. Only returns letters eligible\
        \ for the user"
      operationId: "getLetters"
      produces:
      - "application/json"
      parameters: []
      responses:
        200:
          description: "A Response which indicates a successful Request.  The Response\
            \ may contain \"messages\" that could describe warnings or further information."
          schema:
            $ref: "#/definitions/LettersResponse"
        400:
          description: "There was an error encountered processing the Request.  Response\
            \ will contain a  \"messages\" element that will provide further information\
            \ on the error.  This request shouldn't be retried until corrected."
          schema:
            $ref: "#/definitions/ServiceResponse"
        500:
          description: "There was an error encountered processing the Request.  Response\
            \ will contain a  \"messages\" element that will provide further information\
            \ on the error.  Please retry.  If problem persists, please contact support\
            \ with a copy of the Response."
          schema:
            $ref: "#/definitions/ServiceResponse"
        403:
          description: "The request is not authorized.  Please verify credentials\
            \ used in the request."
  /letters/v1/{letterType}:
    get:
      tags:
      - "letters"
      summary: "Get Letter By Type"
      description: "Returns the letter in PDF format."
      operationId: "getLetterByType"
      produces:
      - "application/json"
      - "application/pdf"
      parameters:
      - name: "letterType"
        in: "path"
        description: "Letter Type"
        required: true
        type: "string"
        enum:
        - "BENEFITSUMMARY"
        - "BENEFITSUMMARYDEPENDENT"
        - "BENEFITVERIFICATION"
        - "CIVILSERVICE"
        - "COMMISSARY"
        - "PROOFOFSERVICE"
        - "SERVICEVERIFICATION"
        - "MEDICAREPARTD"
        - "MINIMUMESSENTIALCOVERAGE"
      responses:
        201:
          description: "Actual PDF File, application/pdf"
        400:
          description: "There was an error encountered processing the Request.  Response\
            \ will contain a  \"messages\" element that will provide further information\
            \ on the error.  This request shouldn't be retried until corrected."
          schema:
            $ref: "#/definitions/ServiceResponse"
        500:
          description: "There was an error encountered processing the Request.  Response\
            \ will contain a  \"messages\" element that will provide further information\
            \ on the error.  Please retry.  If problem persists, please contact support\
            \ with a copy of the Response."
          schema:
            $ref: "#/definitions/ServiceResponse"
        403:
          description: "The request is not authorized.  Please verify credentials\
            \ used in the request."
definitions:
  Letter:
    type: "object"
    required:
    - "letterName"
    - "letterType"
    properties:
      letterName:
        type: "string"
      letterType:
        type: "string"
        enum:
        - "BENEFITSUMMARY"
        - "BENEFITSUMMARYDEPENDENT"
        - "BENEFITVERIFICATION"
        - "CIVILSERVICE"
        - "COMMISSARY"
        - "PROOFOFSERVICE"
        - "SERVICEVERIFICATION"
        - "MEDICAREPARTD"
        - "MINIMUMESSENTIALCOVERAGE"
  ServiceResponse:
    type: "object"
    properties:
      messages:
        type: "array"
        items:
          $ref: "#/definitions/Message"
  Message:
    type: "object"
    properties:
      key:
        type: "string"
      text:
        type: "string"
      severity:
        type: "string"
        enum:
        - "FATAL"
        - "ERROR"
        - "WARN"
        - "INFO"
  LettersResponse:
    type: "object"
    required:
    - "letter"
    properties:
      messages:
        type: "array"
        items:
          $ref: "#/definitions/Message"
      letter:
        type: "array"
        items:
          $ref: "#/definitions/Letter"
        maxItems: 10
        minItems: 1
externalDocs:
  description: "API Error Keys"
  url: "ext-docs/lettergenerator-error-keys.html"
  
