version: 2
jobs:
  scrape:
    docker:
      - image: ubuntu:14.04

      # install `jq` because it's required by `algolia/docsearch-scraper`
      - image: stedolan/jq

      - image: algolia/docsearch-scraper

  working_directory: ~/va.gov-team

  steps:
    - checkout

    - run:
      name: Scrape public documentation sources
      # use ALGOLIA_API_KEY and ALGOLIA_APP_ID env variables that were set in CircleCI UI
      command: |
        docker run -it -e "API_KEY=$ALGOLIA_API_KEY" -e "APPLICATION_ID=$ALGOLIA_APP_ID" -e "CONFIG=$(cat docs/docsearch-scraper-config.json | jq -r tostring)" algolia/docsearch-scraper

workflows:
  version: 2
  nightly:
    triggers:
      - schedule:
          # every night around midnight in eastern time
          cron: "0 5 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - scrape
